name: Boop
version: '${version}'
main: cx.june.boop.Boop
api-version: '1.20'
authors: [June]
description: Boop other players!
commands:
  boop:
    description: Boop another player!
    usage: /boop <player>
    permission: boop.use